### ISSUE TITLE
Create linear (and potentially spline) multipliers for the Bay Delta

### ISSUE THREAD

**Issue by qjhart** [ssj-delta-cu/ssj-ucd-metric#2]
We have demonstrated that we can create a set of multipliers for the landsat imagery that we have, in order to create our monthly datasets.  The idea here being that once we have our Kc factors, if we know we want a linear interpolation, we can precalculate the percentages of each daily component.  We can then apply those to the Kc values from our Metric results, and the simply multiply our Kc rasters by these factors to determine monthly values.

**Comment by qjhart** [comment]
This has been performed in the EE script, landsat_to_monthly.js.  It currently only supports linear interpolation.  The script is not general, that is you cannot easily use it on other contexts, but the notion of creating an Image Collection that can be joined for the multiplication is a good one.

**Comment by jamorande** [comment]
The inputs used are from 06/25.

**Comment by jamorande** [comment]
- Image inputs are OK and in respective folders.
- Meteorological inputs are fine 
- Elevation values OK
- Same as 9-10, Hot pixel values remain within a reasonable range in the iterations whereas Cold pixel values go crazy due to a exponential increase in a variable called rah. I found a place in the spreadsheet where they suggest to adjust windspeed in cases like this and set a specific lower limit in order to create numerical stability in the values for "Cold rah".
  I'd rather to meet with you to take a decision and see if we can try this.

A
